# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Bezpłatna wersja próbna(982f6556-c78d-4dd7-adac-f5fb1aec84c1)'
    subscriptionId: '982f6556-c78d-4dd7-adac-f5fb1aec84c1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'onpremise-data-loading'
    location: 'Germany West Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/rzodkiewiczmichal/onpremise-data-loading/tree/main/infrastructure'
    deploymentMode: 'Incremental'